name: Deploy to single host in oracle cloud
on: [push]
jobs:
  tests:
    uses: mickvav/biotools/.github/workflows/tests.yml@master

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    environment: Oracle_cloud
    steps:
      - name: Do ssh magic
        shell: bash
        env:
          secrets_private_key: ${{ secrets.PRIVATE_KEY }}
          secrets_username: ${{ secrets.USERNAME }}
          secrets_hostname: ${{ secrets.HOSTNAME }}
        run: | 
          echo $secrets_private_key > identity
          echo "::warning:: Going to oc2"
          echo "${{ secrets.USERNAME }}"
          echo ssh -i identity "${secrets_username}@${secrets_hostname}" "rm -rf biotools.bak; mv biotools biotools.bak; git clone git@github.com:mickvav/biotools.git"
          ssh -i identity "${secrets_username}@${secrets_hostname}" "rm -rf biotools.bak; mv biotools biotools.bak; git clone git@github.com:mickvav/biotools.git"
      - uses: webiny/action-post-run@2.0.1
        id: post-run-command
        with:
          run: rm identity

