name: Deploy to single host in oracle cloud
on: [push]
uses: mickvav/biotools/.github/workflows/tests.yml@master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "{{ secrets.PRIVATE_KEY }}" > identity
          echo "::warning:: Going to oc2"
          ssh -i identity "{{secrets.USERNAME}}@{{secrets.HOSTNAME}}" "rm -rf biotools.bak; mv biotools biotools.bak; git clone git@github.com:mickvav/biotools.git"
        post: rm identity

