name: GitHub run tests
on: [push, pull_request, workflow_call]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - run: python3 -m unittest discover tests/ 'test_*.py'
        
